/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Frank
 */


import controller.TareaController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Tarea;
public class FrameEscritorio extends javax.swing.JFrame {
  private TareaController tareaController = new TareaController();
    /**
     * Creates new form FrameEscritorio
     */
    public FrameEscritorio() {
        initComponents();
          cargarTabla();
    }
    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tbltabla.getModel();
        modelo.setRowCount(0);

        for (Tarea t : tareaController.obtenerTareas()) {
            Object[] fila = new Object[]{
                t.getId(),
                t.getNombre(),
                t.getFecha(),
                t.getDescripcion(),
                t.getEstado()
            };
            modelo.addRow(fila);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ldlnombre = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        btnañadir = new javax.swing.JButton();
        lblfecha = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        lblestado = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ldlnombre.setText("NOMBRE");
        jPanel2.add(ldlnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, -1, -1));

        lbldescripcion.setText("DESCRIPCION");
        jPanel2.add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 35, 71, -1));
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 63, 71, -1));

        btnañadir.setBackground(new java.awt.Color(204, 204, 204));
        btnañadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHECK.png"))); // NOI18N
        btnañadir.setText("Añadir");
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });
        jPanel2.add(btnañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 210, 70));

        lblfecha.setText("FECHA");
        jPanel2.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 37, -1));

        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 103, 71, -1));

        lblestado.setText("ESTADO");
        jPanel2.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, -1, -1));

        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 135, 71, -1));

        lblid.setText("ID");
        jPanel2.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 37, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 6, 71, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 340, 210));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("AppEscritorio");
        jLabel5.setIconTextGap(18);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 30));

        tbltabla.setForeground(new java.awt.Color(102, 255, 102));
        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "FECHA", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 520, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
       try {
            int id = Integer.parseInt(txtid.getText());
            String nombre = txtnombre.getText();
            String fecha = txtfecha.getText();
            String descripcion = txtdescripcion.getText();
            String estado = txtestado.getText();

            if(nombre.isEmpty() || fecha.isEmpty() || descripcion.isEmpty() || estado.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos.");
                return;
            }

            Tarea tarea = new Tarea(id, nombre, fecha, descripcion, estado);
            boolean success = tareaController.añadirTarea(tarea);

            if(success) {
                JOptionPane.showMessageDialog(this, "Tarea añadida correctamente.");
                cargarTabla();

                txtid.setText("");
                txtnombre.setText("");
                txtfecha.setText("");
                txtdescripcion.setText("");
                txtestado.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error al añadir la tarea. ¿ID duplicado?");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero.");
        }
    

    }//GEN-LAST:event_btnañadirActionPerformed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEscritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel ldlnombre;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
